name: Postman Regression Tests

on:
    pull_request:
        branches: ["dev"]
    push:
        branches: ["cicd/integration-env"]

jobs:
    postman-tests:
      runs-on: ubuntu-latest
      timeout-minutes: 10

      services:
          postgres:
            image: postgres

            env:
              POSTGRES_PASSWORD: postgres
              POSTGRES_USER: postgres
              POSTGRES_DB: MangaTracker
            
            options: >-
              --health-cmd pg_isready
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5
            ports:
              - 5432:5432

      steps:
        -
          name: Checkout
          uses: actions/checkout@v3
        -
          name: Install Packages
          run: npm ci
        -
          name: Install newman
          run: npm install -g newman
        -
          name: Create Env File
          run: |
            touch .env
            echo PORT=${{ secrets.TNR_API_PORT }} >> .env
            echo NODE_ENV=${{ secrets.TNR_NODE_ENV }} >> .env
            echo DATABASE_HOST=${{ secrets.TNR_DATABASE_HOST }} >> .env
            echo DATABASE_NAME=${{ secrets.TNR_DATABASE_NAME }} >> .env
            echo DATABASE_USER=${{ secrets.TNR_DATABASE_USER }} >> .env
            echo DATABASE_PASSWORD=${{ secrets.TNR_DATABASE_PASSWORD }} >> .env
            echo DATABASE_PORT=${{ secrets.TNR_DATABASE_PORT }} >> .env
            echo DATABASE_SCHEMA=${{ secrets.TNR_DATABASE_SCHEMA }} >> .env
            echo JWT_KEY=${{ secrets.TNR_JWT_KEY }} >> .env
            echo JWT_KEY_EXPIRES_IN=${{ secrets.TNR_JWT_EXPIRES }} >> .env
            echo JWT_REFRESH_SECRET=${{ secrets.TNR_JWT_REFRESH_KEY }} >> .env
            echo JWT_REFRESH_SECRET_EXPIRES_IN=${{ secrets.TNR_JWT_REFRESH_SECRET_EXPIRES_IN }} >> .env
            echo HTTP_TIMEOUT=${{ secrets.TNR_HTTP_TIMEOUT}} >> .env
            echo HTTP_MAX_REDIRECT=${{ secrets.TNR_HTTP_MAX_REDIRECT }} >> .env
            echo ENABLE_DEBUG_MESSAGES_FOR_API_CLIENT=${{ secrets.TNR_ENABLE_DEBUG_MESSAGES_FOR_API_CLIENT }} >> .env
            echo DISABLE_ERROR_MESSAGES_FOR_API_CLIENT=${{ secrets.TNR_DISABLE_ERROR_MESSAGES_FOR_API_CLIENT }} >> .env
            echo TYPEORM_DEBUG_LOGGING=${{ secrets.TNR_TYPEORM_DEBUG_LOGGING }} >> .env
        -
          name: Run the API and Postman's tests
          run: |
            npm run start:dev &
            sleep 60
            newman run https://api.postman.com/collections/21616667-b4278202-be33-4b8c-a274-5113955e6838?access_key=${{ secrets.POSTMAN_API_ACCESS_KEY }}