name: CI/CD Build & Publish Image

on:
  push:
    branches: [ "master", "integration", "dev" ]

env:
  
  BASE_BRANCH_NAME: ${{ github.base_ref || github.ref_name }}
  BRANCH_NAME: ${BASE_BRANCH_NAME//\//-}

permissions: write-all

jobs:
  publish-manga-tracker-api-image:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Debug branch names
        run: |
            echo "BASE_BRANCH_NAME = $BASE_BRANCH_NAME"
            echo "BRANCH_NAME      = $BRANCH_NAME"
     
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push Docker image
        run: |
          IMAGE=bladeburu/manga-tracker-api:${{ env.BRANCH_NAME }}-latest
          docker build --target production -t $IMAGE .
          docker push $IMAGE

      - name: Rollout on NAS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: | 
            set -x
            TAG="${BRANCH_NAME}-latest"
            echo "▶ Deploying tag: $TAG"
            bash /home/admin/rollout.sh manga-tracker-api "$TAG"
       
            
