name: CI/CD Build & Publish Image

on:
  push:
    branches: [ "master", "integration", "dev" ]

permissions: write-all

jobs:
  publish-manga-tracker-api-image:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v3     

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      
      - name: Build & push Docker image
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          BRANCH_SLUG="${BRANCH_NAME//\//-}"
          TIMESTAMP="$(date +'%Y%m%d%H%M')"
          TAG="${BRANCH_SLUG}-${TIMESTAMP}"

          echo "DEPLOY_TAG=$TAG" >> $GITHUB_ENV
          IMAGE=bladeburu/manga-tracker-api:$TAG
          docker build --target production -t $IMAGE .
          docker push $IMAGE
          echo "DEPLOY_TAG=$TAG" >> $GITHUB_ENV

      - name: Rollout on NAS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: | 
            set -x

            echo "▶ Deploying image tag: $DEPLOY_TAG"
            bash /home/admin/rollout.sh manga-tracker-api "$DEPLOY_TAG"
